### ISSUE TITLE
Input length of input_ids is 2400, but `max_length` is set to 2048. 

### ISSUE THREAD

**Issue by zyb8543d** [yeyupiaoling/Chinese-LLM-Chat#3]
知识库的推理demo，连续问七八次的样子，就会报下面的错误：
Input length of input_ids is 2400, but max_length is set to 2048. This can lead to unexpected behavior. You should consider increasing max_new_tokens.
重启服务后就又可以了，再问的多了就继续报错，

**Comment by yeyupiaoling** [comment]
你多轮的话，它输入长度就变长了。超过了它的限制。
